import type { AccessGroupCode } from "@/features/access/types";
import type { DashboardConfig, DashboardWidget } from "../types";

/**
 * Configuração centralizada do Dashboard por Grupo de Acesso.
 *
 * Fluxo: Grupo → Configuração → Widgets autorizados → Ordem → Dados → Render.
 * Nível 1 (padrão do sistema) está representado aqui. Os Níveis 2
 * (Administrador) e 3 (preferências do usuário) consumirão exatamente este
 * mesmo contrato, sem alteração de código de apresentação.
 */

const CONSOLIDATED_WIDGETS: DashboardWidget[] = [
  {
    code: "kpi.comerciais",
    title: "Indicadores comerciais",
    component: "kpi-group",
    module: "comercial",
    order: 10,
    span: 3,
    visible: true,
    dataKey: "consolidado.kpisComerciais",
  },
  {
    code: "kpi.operacionais",
    title: "Indicadores operacionais",
    component: "kpi-group",
    module: null,
    order: 20,
    span: 3,
    visible: true,
    dataKey: "consolidado.kpisOperacionais",
  },
  {
    code: "chart.vendas",
    title: "Propostas x Pedidos",
    description: "Evolução dos últimos 6 meses",
    component: "chart",
    module: "comercial",
    order: 30,
    span: 2,
    visible: true,
    dataKey: "consolidado.vendas",
  },
  {
    code: "chart.producao",
    title: "Ordens de produção por status",
    description: "Distribuição atual da fábrica",
    component: "chart",
    module: "producao",
    order: 40,
    span: 1,
    visible: true,
    dataKey: "consolidado.producao",
  },
  {
    code: "list.atividades",
    title: "Atividades recentes",
    description: "Últimos eventos registrados na plataforma",
    component: "activity-list",
    module: null,
    order: 50,
    span: 2,
    visible: true,
    dataKey: "consolidado.atividades",
  },
  {
    code: "list.agenda",
    title: "Agenda do dia",
    description: "Compromissos de hoje",
    component: "agenda",
    module: null,
    order: 60,
    span: 1,
    visible: true,
    dataKey: "consolidado.agenda",
  },
  {
    code: "list.pendencias",
    title: "Pendências críticas",
    description: "Itens que aguardam sua ação",
    component: "pending-items",
    module: null,
    order: 70,
    span: 2,
    visible: true,
    dataKey: "consolidado.pendencias",
  },
  {
    code: "acoes.atalhos",
    title: "Atalhos rápidos",
    description: "Acesso direto às áreas",
    component: "quick-actions",
    module: null,
    order: 80,
    span: 1,
    visible: true,
    dataKey: "consolidado.atalhos",
  },
  {
    code: "avisos.gerais",
    title: "Avisos",
    description: "Comunicados internos",
    component: "notices",
    module: null,
    order: 90,
    span: 1,
    visible: true,
    dataKey: "consolidado.avisos",
  },
];

export const DASHBOARD_CONFIGS: Record<AccessGroupCode, DashboardConfig> = {
  administracao: {
    group: "administracao",
    title: "Visão consolidada",
    description: "Visão completa da operação da Brasilab.",
    widgets: CONSOLIDATED_WIDGETS,
  },
  diretoria: {
    group: "diretoria",
    title: "Visão executiva",
    description: "Acompanhamento estratégico da operação.",
    widgets: CONSOLIDATED_WIDGETS,
  },
  comercial: {
    group: "comercial",
    title: "Dashboard Comercial",
    description: "Leads, propostas, conversão e carteira comercial.",
    widgets: [
      {
        code: "comercial.leads.kpis",
        title: "Leads",
        component: "leads-kpis",
        module: "comercial",
        order: 5,
        span: 3,
        visible: true,
        dataKey: "comercial.leads.kpis",
      },
      {
        code: "comercial.leads.agenda",
        title: "Próximos contatos",
        description: "Agenda de Leads sob sua responsabilidade",
        component: "leads-agenda",
        module: "comercial",
        order: 35,
        span: 1,
        visible: true,
        dataKey: "comercial.leads.agenda",
      },
      {
        code: "comercial.kpis",
        title: "Indicadores comerciais",
        component: "kpi-group",
        module: "comercial",
        order: 10,
        span: 3,
        visible: true,
        dataKey: "comercial.kpis",
      },
      {
        code: "comercial.funil",
        title: "Propostas x Pedidos",
        description: "Evolução dos últimos 6 meses",
        component: "chart",
        module: "comercial",
        order: 20,
        span: 2,
        visible: true,
        dataKey: "comercial.funil",
      },
      {
        code: "comercial.vencimentos",
        title: "Propostas próximas do vencimento",
        description: "Acompanhamento de validade",
        component: "deadline-list",
        module: "comercial",
        order: 30,
        span: 1,
        visible: true,
        dataKey: "comercial.vencimentos",
      },
      {
        code: "comercial.atividades",
        title: "Atividades da carteira",
        description: "Eventos recentes do comercial",
        component: "activity-list",
        module: "comercial",
        order: 40,
        span: 2,
        visible: true,
        dataKey: "comercial.atividades",
      },
      {
        code: "comercial.agenda",
        title: "Agenda comercial",
        description: "Compromissos de hoje",
        component: "agenda",
        module: null,
        order: 50,
        span: 1,
        visible: true,
        dataKey: "comercial.agenda",
      },
      {
        code: "comercial.pendencias",
        title: "Pendências comerciais",
        description: "Itens que aguardam sua ação",
        component: "pending-items",
        module: "comercial",
        order: 60,
        span: 2,
        visible: true,
        dataKey: "comercial.pendencias",
      },
    ],
  },
  financeiro: {
    group: "financeiro",
    title: "Dashboard Financeiro",
    description: "Entradas, saídas, títulos e fluxo financeiro.",
    widgets: [
      {
        code: "financeiro.kpis",
        title: "Indicadores financeiros",
        component: "kpi-group",
        module: "financeiro",
        order: 10,
        span: 3,
        visible: true,
        dataKey: "financeiro.kpis",
      },
      {
        code: "financeiro.fluxo",
        title: "Fluxo financeiro",
        description: "Entradas e saídas dos últimos 6 meses",
        component: "chart",
        module: "financeiro",
        order: 20,
        span: 2,
        visible: true,
        dataKey: "financeiro.fluxo",
      },
      {
        code: "financeiro.resumo",
        title: "Resumo de títulos",
        description: "Situação atual da carteira",
        component: "status-summary",
        module: "financeiro",
        order: 30,
        span: 1,
        visible: true,
        dataKey: "financeiro.resumo",
      },
      {
        code: "financeiro.vencimentos",
        title: "Títulos vencendo e vencidos",
        description: "Prioridade de cobrança e pagamento",
        component: "deadline-list",
        module: "financeiro",
        order: 40,
        span: 2,
        visible: true,
        dataKey: "financeiro.vencimentos",
      },
      {
        code: "financeiro.pendencias",
        title: "Pendências financeiras",
        description: "Itens que aguardam sua ação",
        component: "pending-items",
        module: "financeiro",
        order: 50,
        span: 1,
        visible: true,
        dataKey: "financeiro.pendencias",
      },
      {
        code: "financeiro.atividades",
        title: "Atividades recentes",
        description: "Eventos do financeiro",
        component: "activity-list",
        module: "financeiro",
        order: 60,
        span: 2,
        visible: true,
        dataKey: "financeiro.atividades",
      },
    ],
  },
  producao: {
    group: "producao",
    title: "Dashboard de Produção",
    description: "Ordens, prioridades e agenda da fábrica.",
    widgets: [
      {
        code: "producao.kpis",
        title: "Indicadores de produção",
        component: "kpi-group",
        module: "producao",
        order: 10,
        span: 3,
        visible: true,
        dataKey: "producao.kpis",
      },
      {
        code: "producao.status",
        title: "Ordens por status",
        description: "Distribuição atual da fábrica",
        component: "chart",
        module: "producao",
        order: 20,
        span: 2,
        visible: true,
        dataKey: "producao.status",
      },
      {
        code: "producao.resumo",
        title: "Situação das ordens",
        description: "Atrasos e criticidade",
        component: "status-summary",
        module: "producao",
        order: 30,
        span: 1,
        visible: true,
        dataKey: "producao.resumo",
      },
      {
        code: "producao.prioridades",
        title: "Prioridades da fábrica",
        description: "Ordens com entrega próxima",
        component: "deadline-list",
        module: "producao",
        order: 40,
        span: 2,
        visible: true,
        dataKey: "producao.prioridades",
      },
      {
        code: "producao.agenda",
        title: "Agenda da fábrica",
        description: "Compromissos de hoje",
        component: "agenda",
        module: null,
        order: 50,
        span: 1,
        visible: true,
        dataKey: "producao.agenda",
      },
      {
        code: "producao.pendencias",
        title: "Pendências operacionais",
        description: "Itens que aguardam sua ação",
        component: "pending-items",
        module: "producao",
        order: 60,
        span: 2,
        visible: true,
        dataKey: "producao.pendencias",
      },
    ],
  },
  compras: {
    group: "compras",
    title: "Dashboard de Compras",
    description: "Solicitações, cotações e recebimentos.",
    widgets: [
      {
        code: "compras.kpis",
        title: "Indicadores de compras",
        component: "kpi-group",
        module: "compras",
        order: 10,
        span: 3,
        visible: true,
        dataKey: "compras.kpis",
      },
      {
        code: "compras.recebimentos",
        title: "Materiais aguardando recebimento",
        description: "Previsões e atrasos",
        component: "deadline-list",
        module: "compras",
        order: 20,
        span: 2,
        visible: true,
        dataKey: "compras.recebimentos",
      },
      {
        code: "compras.resumo",
        title: "Situação do setor",
        description: "Resumo operacional",
        component: "status-summary",
        module: "compras",
        order: 30,
        span: 1,
        visible: true,
        dataKey: "compras.resumo",
      },
      {
        code: "compras.pendencias",
        title: "Pendências do setor",
        description: "Itens que aguardam sua ação",
        component: "pending-items",
        module: "compras",
        order: 40,
        span: 2,
        visible: true,
        dataKey: "compras.pendencias",
      },
      {
        code: "compras.atividades",
        title: "Atividades recentes",
        description: "Eventos de compras",
        component: "activity-list",
        module: "compras",
        order: 50,
        span: 1,
        visible: true,
        dataKey: "compras.atividades",
      },
    ],
  },
  logistica: {
    group: "logistica",
    title: "Dashboard de Logística",
    description: "Expedição, transporte e instalação.",
    widgets: [
      {
        code: "logistica.kpis",
        title: "Indicadores de logística",
        component: "kpi-group",
        module: "logistica",
        order: 10,
        span: 3,
        visible: true,
        dataKey: "logistica.kpis",
      },
      {
        code: "logistica.agenda",
        title: "Agenda de expedição",
        description: "Compromissos de hoje",
        component: "agenda",
        module: null,
        order: 20,
        span: 1,
        visible: true,
        dataKey: "logistica.agenda",
      },
      {
        code: "logistica.pendencias",
        title: "Pendências de logística",
        description: "Itens que aguardam sua ação",
        component: "pending-items",
        module: "logistica",
        order: 30,
        span: 2,
        visible: true,
        dataKey: "logistica.pendencias",
      },
    ],
  },
  engenharia: {
    group: "engenharia",
    title: "Dashboard de Engenharia",
    description: "Projetos técnicos, fichas e revisões.",
    widgets: [
      {
        code: "engenharia.kpis",
        title: "Indicadores de engenharia",
        component: "kpi-group",
        module: null,
        order: 10,
        span: 3,
        visible: true,
        dataKey: "engenharia.kpis",
      },
      {
        code: "engenharia.pendencias",
        title: "Pendências técnicas",
        description: "Itens que aguardam sua ação",
        component: "pending-items",
        module: null,
        order: 20,
        span: 2,
        visible: true,
        dataKey: "engenharia.pendencias",
      },
      {
        code: "engenharia.atividades",
        title: "Atividades recentes",
        description: "Eventos ligados à produção",
        component: "activity-list",
        module: "producao",
        order: 30,
        span: 1,
        visible: true,
        dataKey: "engenharia.atividades",
      },
    ],
  },
};

export function getDashboardConfig(group: AccessGroupCode): DashboardConfig {
  return DASHBOARD_CONFIGS[group] ?? DASHBOARD_CONFIGS.administracao;
}
