/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as AuthenticatedModuleRouteImport } from './routes/_authenticated/$module'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdministracaoIndexRouteImport } from './routes/_authenticated/administracao/index'
import { Route as AuthenticatedAdministracaoAuditoriaRouteImport } from './routes/_authenticated/administracao/auditoria'
import { Route as AuthenticatedAdministracaoGruposRouteImport } from './routes/_authenticated/administracao/grupos'
import { Route as AuthenticatedAdministracaoPerfisRouteImport } from './routes/_authenticated/administracao/perfis'
import { Route as AuthenticatedAdministracaoPermissoesRouteImport } from './routes/_authenticated/administracao/permissoes'
import { Route as AuthenticatedComercialIndexRouteImport } from './routes/_authenticated/comercial/index'
import { Route as AuthenticatedComercialAgendaRouteImport } from './routes/_authenticated/comercial/agenda'
import { Route as AuthenticatedAdministracaoUsuariosIndexRouteImport } from './routes/_authenticated/administracao/usuarios/index'
import { Route as AuthenticatedAdministracaoUsuariosUserIdRouteImport } from './routes/_authenticated/administracao/usuarios/$userId'
import { Route as AuthenticatedAdministracaoUsuariosNovoRouteImport } from './routes/_authenticated/administracao/usuarios/novo'
import { Route as AuthenticatedComercialLeadsIndexRouteImport } from './routes/_authenticated/comercial/leads/index'
import { Route as AuthenticatedComercialLeadsLeadIdRouteImport } from './routes/_authenticated/comercial/leads/$leadId'
import { Route as AuthenticatedComercialLeadsAprovacoesRouteImport } from './routes/_authenticated/comercial/leads/aprovacoes'
import { Route as AuthenticatedComercialLeadsMeusRouteImport } from './routes/_authenticated/comercial/leads/meus'
import { Route as AuthenticatedComercialLeadsNovoRouteImport } from './routes/_authenticated/comercial/leads/novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedModuleRoute = AuthenticatedModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdministracaoIndexRoute =
  AuthenticatedAdministracaoIndexRouteImport.update({
    id: '/administracao/',
    path: '/administracao/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdministracaoAuditoriaRoute =
  AuthenticatedAdministracaoAuditoriaRouteImport.update({
    id: '/administracao/auditoria',
    path: '/administracao/auditoria',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdministracaoGruposRoute =
  AuthenticatedAdministracaoGruposRouteImport.update({
    id: '/administracao/grupos',
    path: '/administracao/grupos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdministracaoPerfisRoute =
  AuthenticatedAdministracaoPerfisRouteImport.update({
    id: '/administracao/perfis',
    path: '/administracao/perfis',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdministracaoPermissoesRoute =
  AuthenticatedAdministracaoPermissoesRouteImport.update({
    id: '/administracao/permissoes',
    path: '/administracao/permissoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComercialIndexRoute =
  AuthenticatedComercialIndexRouteImport.update({
    id: '/comercial/',
    path: '/comercial/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComercialAgendaRoute =
  AuthenticatedComercialAgendaRouteImport.update({
    id: '/comercial/agenda',
    path: '/comercial/agenda',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdministracaoUsuariosIndexRoute =
  AuthenticatedAdministracaoUsuariosIndexRouteImport.update({
    id: '/administracao/usuarios/',
    path: '/administracao/usuarios/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdministracaoUsuariosUserIdRoute =
  AuthenticatedAdministracaoUsuariosUserIdRouteImport.update({
    id: '/administracao/usuarios/$userId',
    path: '/administracao/usuarios/$userId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdministracaoUsuariosNovoRoute =
  AuthenticatedAdministracaoUsuariosNovoRouteImport.update({
    id: '/administracao/usuarios/novo',
    path: '/administracao/usuarios/novo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComercialLeadsIndexRoute =
  AuthenticatedComercialLeadsIndexRouteImport.update({
    id: '/comercial/leads/',
    path: '/comercial/leads/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComercialLeadsLeadIdRoute =
  AuthenticatedComercialLeadsLeadIdRouteImport.update({
    id: '/comercial/leads/$leadId',
    path: '/comercial/leads/$leadId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComercialLeadsAprovacoesRoute =
  AuthenticatedComercialLeadsAprovacoesRouteImport.update({
    id: '/comercial/leads/aprovacoes',
    path: '/comercial/leads/aprovacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComercialLeadsMeusRoute =
  AuthenticatedComercialLeadsMeusRouteImport.update({
    id: '/comercial/leads/meus',
    path: '/comercial/leads/meus',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComercialLeadsNovoRoute =
  AuthenticatedComercialLeadsNovoRouteImport.update({
    id: '/comercial/leads/novo',
    path: '/comercial/leads/novo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/$module': typeof AuthenticatedModuleRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/administracao/auditoria': typeof AuthenticatedAdministracaoAuditoriaRoute
  '/administracao/grupos': typeof AuthenticatedAdministracaoGruposRoute
  '/administracao/perfis': typeof AuthenticatedAdministracaoPerfisRoute
  '/administracao/permissoes': typeof AuthenticatedAdministracaoPermissoesRoute
  '/comercial/agenda': typeof AuthenticatedComercialAgendaRoute
  '/administracao/': typeof AuthenticatedAdministracaoIndexRoute
  '/comercial/': typeof AuthenticatedComercialIndexRoute
  '/administracao/usuarios/$userId': typeof AuthenticatedAdministracaoUsuariosUserIdRoute
  '/administracao/usuarios/novo': typeof AuthenticatedAdministracaoUsuariosNovoRoute
  '/comercial/leads/$leadId': typeof AuthenticatedComercialLeadsLeadIdRoute
  '/comercial/leads/aprovacoes': typeof AuthenticatedComercialLeadsAprovacoesRoute
  '/comercial/leads/meus': typeof AuthenticatedComercialLeadsMeusRoute
  '/comercial/leads/novo': typeof AuthenticatedComercialLeadsNovoRoute
  '/administracao/usuarios/': typeof AuthenticatedAdministracaoUsuariosIndexRoute
  '/comercial/leads/': typeof AuthenticatedComercialLeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/$module': typeof AuthenticatedModuleRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/administracao/auditoria': typeof AuthenticatedAdministracaoAuditoriaRoute
  '/administracao/grupos': typeof AuthenticatedAdministracaoGruposRoute
  '/administracao/perfis': typeof AuthenticatedAdministracaoPerfisRoute
  '/administracao/permissoes': typeof AuthenticatedAdministracaoPermissoesRoute
  '/comercial/agenda': typeof AuthenticatedComercialAgendaRoute
  '/administracao': typeof AuthenticatedAdministracaoIndexRoute
  '/comercial': typeof AuthenticatedComercialIndexRoute
  '/administracao/usuarios/$userId': typeof AuthenticatedAdministracaoUsuariosUserIdRoute
  '/administracao/usuarios/novo': typeof AuthenticatedAdministracaoUsuariosNovoRoute
  '/comercial/leads/$leadId': typeof AuthenticatedComercialLeadsLeadIdRoute
  '/comercial/leads/aprovacoes': typeof AuthenticatedComercialLeadsAprovacoesRoute
  '/comercial/leads/meus': typeof AuthenticatedComercialLeadsMeusRoute
  '/comercial/leads/novo': typeof AuthenticatedComercialLeadsNovoRoute
  '/administracao/usuarios': typeof AuthenticatedAdministracaoUsuariosIndexRoute
  '/comercial/leads': typeof AuthenticatedComercialLeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/_authenticated/$module': typeof AuthenticatedModuleRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/administracao/auditoria': typeof AuthenticatedAdministracaoAuditoriaRoute
  '/_authenticated/administracao/grupos': typeof AuthenticatedAdministracaoGruposRoute
  '/_authenticated/administracao/perfis': typeof AuthenticatedAdministracaoPerfisRoute
  '/_authenticated/administracao/permissoes': typeof AuthenticatedAdministracaoPermissoesRoute
  '/_authenticated/comercial/agenda': typeof AuthenticatedComercialAgendaRoute
  '/_authenticated/administracao/': typeof AuthenticatedAdministracaoIndexRoute
  '/_authenticated/comercial/': typeof AuthenticatedComercialIndexRoute
  '/_authenticated/administracao/usuarios/$userId': typeof AuthenticatedAdministracaoUsuariosUserIdRoute
  '/_authenticated/administracao/usuarios/novo': typeof AuthenticatedAdministracaoUsuariosNovoRoute
  '/_authenticated/comercial/leads/$leadId': typeof AuthenticatedComercialLeadsLeadIdRoute
  '/_authenticated/comercial/leads/aprovacoes': typeof AuthenticatedComercialLeadsAprovacoesRoute
  '/_authenticated/comercial/leads/meus': typeof AuthenticatedComercialLeadsMeusRoute
  '/_authenticated/comercial/leads/novo': typeof AuthenticatedComercialLeadsNovoRoute
  '/_authenticated/administracao/usuarios/': typeof AuthenticatedAdministracaoUsuariosIndexRoute
  '/_authenticated/comercial/leads/': typeof AuthenticatedComercialLeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/entrar'
    | '/recuperar-senha'
    | '/$module'
    | '/dashboard'
    | '/administracao/auditoria'
    | '/administracao/grupos'
    | '/administracao/perfis'
    | '/administracao/permissoes'
    | '/comercial/agenda'
    | '/administracao/'
    | '/comercial/'
    | '/administracao/usuarios/$userId'
    | '/administracao/usuarios/novo'
    | '/comercial/leads/$leadId'
    | '/comercial/leads/aprovacoes'
    | '/comercial/leads/meus'
    | '/comercial/leads/novo'
    | '/administracao/usuarios/'
    | '/comercial/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/entrar'
    | '/recuperar-senha'
    | '/$module'
    | '/dashboard'
    | '/administracao/auditoria'
    | '/administracao/grupos'
    | '/administracao/perfis'
    | '/administracao/permissoes'
    | '/comercial/agenda'
    | '/administracao'
    | '/comercial'
    | '/administracao/usuarios/$userId'
    | '/administracao/usuarios/novo'
    | '/comercial/leads/$leadId'
    | '/comercial/leads/aprovacoes'
    | '/comercial/leads/meus'
    | '/comercial/leads/novo'
    | '/administracao/usuarios'
    | '/comercial/leads'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/entrar'
    | '/recuperar-senha'
    | '/_authenticated/$module'
    | '/_authenticated/dashboard'
    | '/_authenticated/administracao/auditoria'
    | '/_authenticated/administracao/grupos'
    | '/_authenticated/administracao/perfis'
    | '/_authenticated/administracao/permissoes'
    | '/_authenticated/comercial/agenda'
    | '/_authenticated/administracao/'
    | '/_authenticated/comercial/'
    | '/_authenticated/administracao/usuarios/$userId'
    | '/_authenticated/administracao/usuarios/novo'
    | '/_authenticated/comercial/leads/$leadId'
    | '/_authenticated/comercial/leads/aprovacoes'
    | '/_authenticated/comercial/leads/meus'
    | '/_authenticated/comercial/leads/novo'
    | '/_authenticated/administracao/usuarios/'
    | '/_authenticated/comercial/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  EntrarRoute: typeof EntrarRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$module': {
      id: '/_authenticated/$module'
      path: '/$module'
      fullPath: '/$module'
      preLoaderRoute: typeof AuthenticatedModuleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/administracao/': {
      id: '/_authenticated/administracao/'
      path: '/administracao'
      fullPath: '/administracao/'
      preLoaderRoute: typeof AuthenticatedAdministracaoIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/administracao/auditoria': {
      id: '/_authenticated/administracao/auditoria'
      path: '/administracao/auditoria'
      fullPath: '/administracao/auditoria'
      preLoaderRoute: typeof AuthenticatedAdministracaoAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/administracao/grupos': {
      id: '/_authenticated/administracao/grupos'
      path: '/administracao/grupos'
      fullPath: '/administracao/grupos'
      preLoaderRoute: typeof AuthenticatedAdministracaoGruposRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/administracao/perfis': {
      id: '/_authenticated/administracao/perfis'
      path: '/administracao/perfis'
      fullPath: '/administracao/perfis'
      preLoaderRoute: typeof AuthenticatedAdministracaoPerfisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/administracao/permissoes': {
      id: '/_authenticated/administracao/permissoes'
      path: '/administracao/permissoes'
      fullPath: '/administracao/permissoes'
      preLoaderRoute: typeof AuthenticatedAdministracaoPermissoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comercial/': {
      id: '/_authenticated/comercial/'
      path: '/comercial'
      fullPath: '/comercial/'
      preLoaderRoute: typeof AuthenticatedComercialIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comercial/agenda': {
      id: '/_authenticated/comercial/agenda'
      path: '/comercial/agenda'
      fullPath: '/comercial/agenda'
      preLoaderRoute: typeof AuthenticatedComercialAgendaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/administracao/usuarios/': {
      id: '/_authenticated/administracao/usuarios/'
      path: '/administracao/usuarios'
      fullPath: '/administracao/usuarios/'
      preLoaderRoute: typeof AuthenticatedAdministracaoUsuariosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/administracao/usuarios/$userId': {
      id: '/_authenticated/administracao/usuarios/$userId'
      path: '/administracao/usuarios/$userId'
      fullPath: '/administracao/usuarios/$userId'
      preLoaderRoute: typeof AuthenticatedAdministracaoUsuariosUserIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/administracao/usuarios/novo': {
      id: '/_authenticated/administracao/usuarios/novo'
      path: '/administracao/usuarios/novo'
      fullPath: '/administracao/usuarios/novo'
      preLoaderRoute: typeof AuthenticatedAdministracaoUsuariosNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comercial/leads/': {
      id: '/_authenticated/comercial/leads/'
      path: '/comercial/leads'
      fullPath: '/comercial/leads/'
      preLoaderRoute: typeof AuthenticatedComercialLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comercial/leads/$leadId': {
      id: '/_authenticated/comercial/leads/$leadId'
      path: '/comercial/leads/$leadId'
      fullPath: '/comercial/leads/$leadId'
      preLoaderRoute: typeof AuthenticatedComercialLeadsLeadIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comercial/leads/aprovacoes': {
      id: '/_authenticated/comercial/leads/aprovacoes'
      path: '/comercial/leads/aprovacoes'
      fullPath: '/comercial/leads/aprovacoes'
      preLoaderRoute: typeof AuthenticatedComercialLeadsAprovacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comercial/leads/meus': {
      id: '/_authenticated/comercial/leads/meus'
      path: '/comercial/leads/meus'
      fullPath: '/comercial/leads/meus'
      preLoaderRoute: typeof AuthenticatedComercialLeadsMeusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comercial/leads/novo': {
      id: '/_authenticated/comercial/leads/novo'
      path: '/comercial/leads/novo'
      fullPath: '/comercial/leads/novo'
      preLoaderRoute: typeof AuthenticatedComercialLeadsNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedModuleRoute: typeof AuthenticatedModuleRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdministracaoAuditoriaRoute: typeof AuthenticatedAdministracaoAuditoriaRoute
  AuthenticatedAdministracaoGruposRoute: typeof AuthenticatedAdministracaoGruposRoute
  AuthenticatedAdministracaoPerfisRoute: typeof AuthenticatedAdministracaoPerfisRoute
  AuthenticatedAdministracaoPermissoesRoute: typeof AuthenticatedAdministracaoPermissoesRoute
  AuthenticatedComercialAgendaRoute: typeof AuthenticatedComercialAgendaRoute
  AuthenticatedAdministracaoIndexRoute: typeof AuthenticatedAdministracaoIndexRoute
  AuthenticatedComercialIndexRoute: typeof AuthenticatedComercialIndexRoute
  AuthenticatedAdministracaoUsuariosUserIdRoute: typeof AuthenticatedAdministracaoUsuariosUserIdRoute
  AuthenticatedAdministracaoUsuariosNovoRoute: typeof AuthenticatedAdministracaoUsuariosNovoRoute
  AuthenticatedComercialLeadsLeadIdRoute: typeof AuthenticatedComercialLeadsLeadIdRoute
  AuthenticatedComercialLeadsAprovacoesRoute: typeof AuthenticatedComercialLeadsAprovacoesRoute
  AuthenticatedComercialLeadsMeusRoute: typeof AuthenticatedComercialLeadsMeusRoute
  AuthenticatedComercialLeadsNovoRoute: typeof AuthenticatedComercialLeadsNovoRoute
  AuthenticatedAdministracaoUsuariosIndexRoute: typeof AuthenticatedAdministracaoUsuariosIndexRoute
  AuthenticatedComercialLeadsIndexRoute: typeof AuthenticatedComercialLeadsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedModuleRoute: AuthenticatedModuleRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdministracaoAuditoriaRoute:
    AuthenticatedAdministracaoAuditoriaRoute,
  AuthenticatedAdministracaoGruposRoute: AuthenticatedAdministracaoGruposRoute,
  AuthenticatedAdministracaoPerfisRoute: AuthenticatedAdministracaoPerfisRoute,
  AuthenticatedAdministracaoPermissoesRoute:
    AuthenticatedAdministracaoPermissoesRoute,
  AuthenticatedComercialAgendaRoute: AuthenticatedComercialAgendaRoute,
  AuthenticatedAdministracaoIndexRoute: AuthenticatedAdministracaoIndexRoute,
  AuthenticatedComercialIndexRoute: AuthenticatedComercialIndexRoute,
  AuthenticatedAdministracaoUsuariosUserIdRoute:
    AuthenticatedAdministracaoUsuariosUserIdRoute,
  AuthenticatedAdministracaoUsuariosNovoRoute:
    AuthenticatedAdministracaoUsuariosNovoRoute,
  AuthenticatedComercialLeadsLeadIdRoute:
    AuthenticatedComercialLeadsLeadIdRoute,
  AuthenticatedComercialLeadsAprovacoesRoute:
    AuthenticatedComercialLeadsAprovacoesRoute,
  AuthenticatedComercialLeadsMeusRoute: AuthenticatedComercialLeadsMeusRoute,
  AuthenticatedComercialLeadsNovoRoute: AuthenticatedComercialLeadsNovoRoute,
  AuthenticatedAdministracaoUsuariosIndexRoute:
    AuthenticatedAdministracaoUsuariosIndexRoute,
  AuthenticatedComercialLeadsIndexRoute: AuthenticatedComercialLeadsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  EntrarRoute: EntrarRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
